# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-27 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('pizza_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('pizza_size', models.IntegerField()),
                ('customer_name', models.TextField()),
                ('customer_address', models.TextField()),
            ],
        ),
    ]
